{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebi.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nebi.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
