[workspace]
authors = ["Adam Lewis <23342526+Adam-D-Lewis@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "data-science"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"
numpy = ">=2.4.1,<3"
pandas = "2.*"
fastapi = ">=0.128.0,<0.129"

[environments]
test = ["test"]

[feature.test.dependencies]
pytest = "*"
